In [ ]:
#PALINDROMES:

movie = "desserts I stressed"
# Get the word
movie_title = movie[11:30]
# Obtain the palindrome
palindrome = movie_title[::-1]
# Print the word if it's a palindrome
if movie_title == palindrome:
	print(movie_title)

In [21]:
#SPLITTING
my_string = "This string will be split" #\n \r \"...\"
s2=my_string.split(sep=" ", maxsplit=2) #or .rsplit()
s = "dadadadumppa\nskeekit"
print(s.split()) #splitlines
t=my_string.split("i",1)
s3 =my_string.join(s2)

['dadadadumppa', 'skeekit']


In [41]:
# how do I create another list of odds out odds & evens, and another list of instead of evens, they're just zeros?
import numpy as np
x = np.array([1,22,34,2,34,1243,2342,342,5,425,43,4325])
boolean_mask = x %2 == 0
print(boolean_mask)
z = x[boolean_mask]
x[boolean_mask] = 0
y = x[x%2==1]
print(y)
print(z)
print(x)
type(boolean_mask)


[False  True  True  True  True False  True  True False False False False]
[   1 1243    5  425   43 4325]
[  22   34    2   34 2342  342]
[   1    0    0    0    0 1243    0    0    5  425   43 4325]


numpy.ndarray